apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    deployment: app
spec:
  selector:
    matchLabels:
      pod: app
  replicas: 1
  template:
    metadata:
      labels:
        pod: app
    spec:
      containers:
      - name: app
        image: gcr.io/gke-fatafat-mub/my_djago_app:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000