apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    deployment: app
spec:
  selector:
    matchLabels:
      pod: app
  replicas: 1
  template:
    metadata:
      labels:
        pod: app
    spec:
      containers:
      - name: app
        image: gcr.io/gke--build/testing
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        ports:
        - containerPort: 8000