steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my_djago_app:$_TAG', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my_djago_app:$_TAG']
# Create Deployment and Service in yaml conf files
# make sure to also change/update the _TAG inside ./app_deployment.yaml file
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', './app_deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
substitutions:
  _TAG: v1.0.0